### ISSUE TITLE
Tags cannot be removed by Finder

### ISSUE THREAD

**Issue by ctismer** [andrewp-as-is/mac-tag.py#1]
This is a really nice program, but it has a little glitch in the examples:
When tags are set programmatically, they cannot be reset by editing tags in Finder.

Why?
Finder uses Upper case tag names, mac_tag.py uses lowercase.
You should update your examples to use Uppercase and put a note into the
description that this is a Finder-inconsequence that it shows the tags ignoring
the case, but fails to remove a lowercase attribute.

**Comment by andrewpetrochenkov** [comment]
thx. examples updated
